name: 'Setup Incus Tools'
description: 'Install incus-extra and related tools from the Zabbly repository'

inputs:
  extra-packages:
    description: 'Additional packages to install (space-separated)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Setup Zabbly repository
      shell: bash
      run: |
        sudo mkdir -p /etc/apt/keyrings
        sudo curl -fsSL https://pkgs.zabbly.com/key.asc -o /etc/apt/keyrings/zabbly.asc
        sudo sh -c 'cat > /etc/apt/sources.list.d/zabbly-incus-stable.sources <<EOF
        Enabled: yes
        Types: deb
        URIs: https://pkgs.zabbly.com/incus/stable
        Suites: $(. /etc/os-release && echo ${VERSION_CODENAME})
        Components: main
        Architectures: $(dpkg --print-architecture)
        Signed-By: /etc/apt/keyrings/zabbly.asc
        EOF'

    - name: Install packages
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y incus-extra ${{ inputs.extra-packages }}

    - name: Verify installation
      shell: bash
      run: |
        distrobuilder --version
        incus-simplestreams --version
