name: 'Setup Incus Tools'
description: 'Install incus-simplestreams for registry management'

inputs:
  extra-packages:
    description: 'Additional packages to install (space-separated)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Check for Incus
      shell: bash
      run: |
        if ! command -v incus &> /dev/null; then
          echo "Error: Incus not found. This action requires Incus to be pre-installed."
          echo "Self-hosted runners should have Incus installed."
          exit 1
        fi
        incus --version

    - name: Setup Zabbly repository for incus-simplestreams
      shell: bash
      run: |
        if ! command -v incus-simplestreams &> /dev/null; then
          echo "Installing incus-simplestreams from Zabbly repository..."
          sudo mkdir -p /etc/apt/keyrings
          sudo curl -fsSL https://pkgs.zabbly.com/key.asc -o /etc/apt/keyrings/zabbly.asc
          sudo sh -c 'cat > /etc/apt/sources.list.d/zabbly-incus-stable.sources <<EOF
        Enabled: yes
        Types: deb
        URIs: https://pkgs.zabbly.com/incus/stable
        Suites: $(. /etc/os-release && echo ${VERSION_CODENAME})
        Components: main
        Architectures: $(dpkg --print-architecture)
        Signed-By: /etc/apt/keyrings/zabbly.asc
        EOF'
          sudo apt-get update
          sudo apt-get install -y incus-extra ${{ inputs.extra-packages }}
        else
          echo "incus-simplestreams already installed"
          if [ -n "${{ inputs.extra-packages }}" ]; then
            sudo apt-get update
            sudo apt-get install -y ${{ inputs.extra-packages }}
          fi
        fi

    - name: Verify installation
      shell: bash
      run: |
        incus-simplestreams --version
